<?xml version="1.0"?>

<!DOCTYPE sql-list
[
  <!ELEMENT sql-list (sql)+>
  <!ELEMENT sql (value,(parameter)*,(result)?)>
  <!ATTLIST sql
    id ID #IMPLIED
    dao CDATA #REQUIRED
    name CDATA #REQUIRED
    type (select | insert | update | delete | select-for-update) #REQUIRED
    implementation (mysql | oracle | postgres | odbc | mock | xml | all) #REQUIRED>

  <!ELEMENT value (#PCDATA)>
  <!ELEMENT parameter EMPTY>
  <!ATTLIST parameter
    index CDATA #REQUIRED
    type  CDATA #REQUIRED>
  <!ELEMENT result (property)+>
  <!ATTLIST result
    class CDATA #IMPLIED
    matches (single | multiple) #REQUIRED>
  <!ELEMENT property EMPTY>
  <!ATTLIST property
    column_name CDATA #IMPLIED
    index CDATA #IMPLIED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
]>

<sql-list>
  <sql
    id="customer1"
    dao="customer"
    name="find-customer-by-customer-id"
    type="select"
    implementation="all">
    <value>select * from customers where customer_id = ?</value>
    <parameter index="1" type="long"/>
    <result matches="single">
      <property column_name="customer_id" type="long"/>
      <property column_name="name" type="String"/>
    </result>
  </sql>
  <sql
    name="find-customer-by-person-last-name"
    dao="customer"
    implementation="all"
    type="select">
    <value>select c.customer_id, p.name from customers c, people p where p.last_name like ?</value>
    <parameter index="1" type="String"/>
    <result class="com.foo.bar.dao.CustomerBean" matches="multiple">
      <property column_name="c.customer_id" name="customerId" type="long"/>
      <property column_name="p.name" name="personName" type="String"/>
    </result>
  </sql>
  <sql
    name="insert-test"
    dao="customer"
    implementation="all"
    type="insert">
    <value>insert into customers (customer_id, name) values (?, "test")</value>
    <parameter index="1" type="long"/>
  </sql>
</sql-list>
