<?xml version="1.0"?>

<!DOCTYPE sql-list
[
  <!ELEMENT sql-list (sql+,parameter-list,result-list,property-list,flag-list)>
  <!ELEMENT sql (description,value,parameter-ref,result-ref?,connection-flags-ref?,statement-flags-ref?,resultset-flags-ref?)>
  <!ATTLIST sql
    id ID #REQUIRED
    dao CDATA #REQUIRED
    name CDATA #REQUIRED
    type (select | insert | update | delete | select-for-update) #REQUIRED
    implementation (mysql | oracle | postgres | odbc | all-jdbc | mock | xml | all) #REQUIRED
    validate (true | false) #REQUIRED>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT value (#PCDATA)>
  <!ELEMENT parameter-ref EMPTY>
  <!ATTLIST parameter-ref
    id IDREF #REQUIRED>
  <!ELEMENT result-ref EMPTY>
  <!ATTLIST result-ref
    id IDREF #REQUIRED>
  <!ELEMENT connection-flags-ref EMPTY>
  <!ATTLIST connection-flags-ref
    id IDREF #REQUIRED>
  <!ELEMENT statement-flags-ref EMPTY>
  <!ATTLIST statement-flags-ref
    id IDREF #REQUIRED>
  <!ELEMENT resultset-flags-ref EMPTY>
  <!ATTLIST resultset-flags-ref
    id IDREF #REQUIRED>
  <!ELEMENT parameter-list (parameter)*>
  <!ELEMENT parameter EMPTY>
  <!ATTLIST parameter
    id ID #REQUIRED
    index CDATA #REQUIRED
    type  CDATA #REQUIRED
    name  CDATA #REQUIRED
    validation-value CDATA #REQUIRED>
  <!ELEMENT result-list (result)*>
  <!ELEMENT result (property-ref)*>
  <!ATTLIST result
    id ID #REQUIRED
    class CDATA #IMPLIED
    matches (none | single | multiple) #REQUIRED
    provider CDATA #IMPLIED>
  <!ELEMENT property-ref EMPTY>
  <!ATTLIST property-ref
    id IDREF #REQUIRED>
  <!ELEMENT property-list (property)*>
  <!ELEMENT property EMPTY>
  <!ATTLIST property
    id ID #REQUIRED
    column_name CDATA #IMPLIED
    index CDATA #IMPLIED
    name CDATA #IMPLIED
    type CDATA #REQUIRED>
  <!ELEMENT flag-list (connection-flags*,statement-flags*,resultset-flags*)>
  <!ELEMENT connection-flags EMPTY>
  <!ATTLIST connection-flags
    id ID #REQUIRED
    transactionisolation (  TRANSACTION_NONE
                          | TRANSACTION_READ_COMMITTED
                          | TRANSACTION_READ_UNCOMMITTED
                          | TRANSACTION_REPEATABLE_READ
                          | TRANSACTION_SERIALIZABLE ) #REQUIRED>
  <!ELEMENT statement-flags EMPTY>
  <!ATTLIST statement-flags
    id ID #REQUIRED
    autogeneratedkeys (NO_GENERATED_KEYS | RETURN_GENERATED_KEYS) #IMPLIED
    fetchsize CDATA #IMPLIED
    maxfieldsize CDATA #IMPLIED
    maxrows CDATA #IMPLIED
    querytimeout CDATA #IMPLIED
    fetchdirection (FETCH_FORWARD | FETCH_REVERSE | FETCH_UNKNOWN) #IMPLIED
    escapeprocessing (true | false) #IMPLIED
    moreresults (CLOSE_CURRENT_RESULT | KEEP_CURRENT_RESULT | CLOSE_ALL_RESULTS) #IMPLIED
    cursorname CDATA #IMPLIED>
  <!ELEMENT resultset-flags EMPTY>
  <!ATTLIST resultset-flags
    id ID #REQUIRED
    type (TYPE_FORWARD_ONLY | TYPE_SCROLL_INSENSITIVE | TYPE_SCROLL_SENSITIVE) #IMPLIED
    concurrency (CONCUR_READ_ONLY | CONCUR_UPDATABLE) #IMPLIED
    holdability (HOLD_CURSORS_OVER_COMMIT | CLOSE_CURSORS_AT_COMMIT) #IMPLIED>
]>

<sql-list>
  <sql
    id="find-bank-accounts-by-user-id"
    dao="um_bank_account"
    name="find-bank-account-by-user-id"
    type="select"
    implementation="all"
    validate="true">
    <description>Retrieves the bank accounts of a user</description>
    <value>select * from um_bank_accounts where user_id = ?</value>
    <parameter-ref id="long-parameter-1"/>
    <result-ref id="find-bank-account-by-user-id.result"/>
  </sql>

  <parameter-list>
    <parameter
      id="long-parameter-1"
      index="1"
      type="long"
      name="id"
      validation-value="987"/>
  </parameter-list>

  <result-list>
    <result
      id="find-bank-account-by-user-id.result"
      class="com.foo.bar.vo.UmBankAccountValueObject"
      matches="multiple">
      <property-ref
        id="find-bank-account-by-user-id.bank-account-id.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-type-id.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-user-id.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-payment-method-status-id.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-bank-code.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-branch.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-control-digit.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-account-number.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-lastmodified.property"/>
      <property-ref
        id="find-bank-account-by-user-id.bank-account-creationdate.property"/>
    </result>
  </result-list>

  <property-list>
    <property
      id="find-bank-account-by-user-id.bank-account-id.property"
      column_name="bank_account_id"
      type="long"/>
    <property
      id="find-bank-account-by-user-id.bank-account-type-id.property"
      column_name="bank_account_type_id"
      type="long"/>
    <property
      id="find-bank-account-by-user-id.bank-account-user-id.property"
      column_name="user_id"
      type="long"/>
    <property
      id="find-bank-account-by-user-id.bank-account-payment-method-status-id.property"
      column_name="payment_method_status_id"
      type="long"/>
    <property
      id="find-bank-account-by-user-id.bank-account-bank-code.property"
      column_name="bank_code"
      type="String"/>
    <property
      id="find-bank-account-by-user-id.bank-account-branch.property"
      column_name="branch"
      type="String"/>
    <property
      id="find-bank-account-by-user-id.bank-account-control-digit.property"
      column_name="control_digit"
      type="String"/>
    <property
      id="find-bank-account-by-user-id.bank-account-account-number.property"
      column_name="account_number"
      type="String"/>
    <property
      id="find-bank-account-by-user-id.bank-account-lastmodified.property"
      column_name="lastmodified"
      type="Date"/>
    <property
      id="find-bank-account-by-user-id.bank-account-creationdate.property"
      column_name="creationdate"
      type="Date"/>
  </property-list>

  <flag-list>
    <connection-flags
      id="connection-flags.find-by-primary-key"
      transactionisolation="TRANSACTION_READ_COMMITTED"/>
    <connection-flags
      id="connection-flags.default"
      transactionisolation="TRANSACTION_NONE"/>
    <connection-flags
      id="connection-flag-transaction-none"
      transactionisolation="TRANSACTION_NONE"/>
    <connection-flags
      id="connection-flag-transaction-read-committed"
      transactionisolation="TRANSACTION_READ_COMMITTED"/>
    <connection-flags
      id="connection-flag-transaction-read-uncommitted"
      transactionisolation="TRANSACTION_READ_UNCOMMITTED"/>
    <connection-flags
      id="connection-flag-transaction-repeatable-read"
      transactionisolation="TRANSACTION_REPEATABLE_READ"/>
    <connection-flags
      id="connection-flag-transaction-serializable"
      transactionisolation="TRANSACTION_TRANSACTION_SERIALIZABLE"/>
    <statement-flags
      id="statement-flags.default"
      autogeneratedkeys="NO_GENERATED_KEYS"/>
    <statement-flags
      id="find-customer-for-update-statement-flags"
      autogeneratedkeys="NO_GENERATED_KEYS"
      fetchsize="10"
      maxfieldsize="1000"
      maxrows="10"
      querytimeout="30"
      fetchdirection="FETCH_FORWARD"
      escapeprocessing="false"
      moreresults="CLOSE_ALL_RESULTS"/>
    <resultset-flags
      id="resultset-flags.default"
      type="TYPE_FORWARD_ONLY"
      concurrency="CONCUR_UPDATABLE"
      holdability="CLOSE_CURSORS_AT_COMMIT"/>
    <resultset-flags
      id="find-customer-for-update-resultset-flags"
      type="TYPE_FORWARD_ONLY"
      concurrency="CONCUR_UPDATABLE"
      holdability="CLOSE_CURSORS_AT_COMMIT"/>
  </flag-list>
</sql-list>
